export const colors = [
    { title: 'White', hex: '#FFFFFF' },
    { title: 'Ash', hex: '#DEDEDE' },
    { title: 'Sports Grey', hex: '#A4A4A4' },
    { title: 'Charcoal', hex: '#635F5C' },
    { title: 'Dark Heather', hex: '#474747' },
    { title: 'Black', hex: '#1C1C1C' },
    { title: 'Azalea', hex: '#F57B9A' },
    { title: 'Ice Grey', hex: '#CECECE' },
    { title: 'Gravel', hex: '#A4A09F' },
    { title: 'Graphite Heather', hex: '#645A59' },
    { title: 'Heather Red', hex: '#D42B42' },
    { title: 'Garnet', hex: '#5F1618' },
    { title: 'Cardinal Red', hex: '#821B2E' },
    { title: 'Maroon', hex: '#501E1F' },
    { title: 'Tangerine', hex: '#E87024' },
    { title: 'Sunset', hex: '#D85C3A' },
    { title: 'Antique Orange', hex: '#DF5C40' },
    { title: 'Safety Orange', hex: '#EF5C00' },
    { title: 'Orange', hex: '#E83D09' },
    { title: 'Tennessee Orange', hex: '#EB6D19' },
    { title: 'Texas Orange', hex: '#A24319' },
    { title: 'Old Gold', hex: '#AF804A' },
    { title: 'Cornsilk', hex: '#E6DC74' },
    { title: 'Yellow Haze', hex: '#F4D49B' },
    { title: 'Daisy', hex: '#F5B122' },
    { title: 'Gold', hex: '#F59400' },
    { title: 'Safety Green', hex: '#E8F81B' },
    { title: 'Neon Green', hex: '#A2EE6D' },
    { title: 'Lime', hex: '#96C93E' },
    { title: 'Kiwi', hex: '#919D53' },
    { title: 'Mint Green', hex: '#9ED299' },
    { title: 'Irish Green', hex: '#2C8B47' },
    { title: 'Electric Green', hex: '#45A538' },
    { title: 'Turf Green', hex: '#2C5823' },
    { title: 'Military Green', hex: '#53553F' },
    { title: 'Heather Military Green', hex: '#5C5D4B' },
    { title: 'Forest', hex: '#344A2D' },
    { title: 'Tweed', hex: '#3B3B3D' },
    { title: 'Antique Jade Dome', hex: '#017C7A' },
    { title: 'Tropical Blue', hex: '#008998' },
    { title: 'Sky', hex: '#A6D7DC' },
    { title: 'Light Blue', hex: '#C0D0DF' },
    { title: 'Carolina Blue', hex: '#9CABC9' },
    { title: 'Heather Sapphire', hex: '#479EBF' },
    { title: 'Sapphire', hex: '#318DB2' },
    { title: 'Antique Sapphire', hex: '#036F9D' },
    { title: 'Royal', hex: '#1B3D7F' },
    { title: 'Neon Blue', hex: '#183882' },
    { title: 'Cobalt', hex: '#2E2562' },
    { title: 'Indigo', hex: '#567279' },
    { title: 'Midnight', hex: '#052B38' },
    { title: 'Heather Navy', hex: '#383A47' },
    { title: 'Navy', hex: '#313447' },
    { title: 'Blackberry', hex: '#292343' },
    { title: 'Lilac', hex: '#473569' },
    { title: 'Violet', hex: '#87799C' },
    { title: 'Purple', hex: '#3F1C50' },
    { title: 'Natural', hex: '#EFE6D1' },
    { title: 'Sand', hex: '#CDBF9F' },
    { title: 'Brown Savana', hex: '#8B756A' },
    { title: 'Dark Chocolate', hex: '#443321' },
];

export const designs = []

;